- name: play level variables
  hosts: local
  connection: local
  vars:
    COURS: "Devops with AWS"
    DURATION: "140HRS"
    TRAINER: "Siva"
  tasks:
  - name: print variables
    ansible.biltin.debug:
      msg: "course is: {{ COURSE }}, Trainer is: {{ TRAINER }}""

